# Generated by Django 6.0.1 on 2026-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaGravatai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=20)),
                ('sexo_outro', models.CharField(blank=True, max_length=100, null=True)),
                ('faixa_etaria', models.CharField(choices=[('16-24', '16 a 24 anos'), ('25-34', '25 a 34 anos'), ('35-44', '35 a 44 anos'), ('45-59', '45 a 59 anos'), ('60+', '60 anos ou mais')], max_length=20)),
                ('escolaridade', models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('Fundamental', 'Fundamental'), ('Medio', 'Ensino Médio'), ('Superior', 'Superior'), ('Pos', 'Pós-graduação')], max_length=50)),
                ('ocupacao', models.CharField(choices=[('CLT', 'CLT'), ('Autonomo', 'Autônomo'), ('Empresario', 'Empresário'), ('Servidor', 'Servidor Público'), ('Estudante', 'Estudante'), ('Desempregado', 'Desempregado/Aposentado')], max_length=50)),
                ('candidatos_poderia_votar', models.TextField(verbose_name='Poderia Votar')),
                ('candidato_voto_hoje', models.CharField(max_length=100, verbose_name='Voto Hoje')),
                ('candidatos_rejeicao', models.TextField(verbose_name='Rejeição')),
                ('candidato_governador', models.CharField(max_length=100)),
                ('renda_familiar', models.CharField(choices=[('Ate 1', 'Até 1 SM'), ('1 a 2', '1 a 2 SM'), ('2 a 5', '2 a 5 SM'), ('5 a 10', '5 a 10 SM'), ('Mais 10', 'Mais de 10 SM'), ('NaoResponder', 'Não responder')], max_length=50)),
                ('nome', models.CharField(max_length=150)),
                ('whatsapp', models.CharField(max_length=20)),
            ],
        ),
    ]
