# Generated by Django 6.0.1 on 2026-01-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisagravatai',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
