# Generated by Django 6.0.1 on 2026-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_pesquisagravatai_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisagravatai',
            name='regiao_residencia',
            field=models.CharField(default='Não Informado', max_length=150),
            preserve_default=False,
        ),
    ]
