# Generated by Django 6.0.1 on 2026-04-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_pesquisagravatai_regiao_residencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisagravatai',
            name='avaliacao_zaffallon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pesquisagravatai',
            name='rumo_governo_estado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pesquisagravatai',
            name='voto_presidente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
