# Generated by Django 6.0.1 on 2026-06-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_pesquisagravatai_avaliacao_zaffallon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisagravatai',
            name='voto_senador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
