# Generated by Django 6.0.1 on 2026-08-02 19:45
# (mão na massa: split manualmente em 3 migrações — cria os models novos aqui,
# migra os dados em 0007, só remove as colunas antigas em 0008 — pra dar pra
# validar os dados migrados antes de apagar a fonte original.)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_pesquisagravatai_voto_senador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Identificador interno estável — não mude depois que a pergunta já tiver respostas.', max_length=60, unique=True)),
                ('label', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('category', models.CharField(blank=True, help_text='Ex: "Intenção de voto", "Perfil demográfico". Deixe em branco pra cair em "Outras perguntas".', max_length=100, verbose_name='Categoria (agrupa no dashboard)')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='Texto de apoio (opcional)')),
                ('question_type', models.CharField(choices=[('radio', 'Escolha única'), ('checkbox_multi', 'Múltipla escolha'), ('text', 'Texto curto'), ('number', 'Número')], default='radio', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatória')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa no totem')),
                ('is_system', models.BooleanField(default=False, editable=False, help_text='Campo de identificação do respondente (nome/whatsapp) — não pode ser excluído.')),
                ('depends_on_value', models.CharField(blank=True, help_text="Preencha junto com 'Só exibir se a pergunta' para pular esta pergunta condicionalmente.", max_length=255, verbose_name='...tiver a resposta')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='survey.question', verbose_name='Só exibir se a pergunta')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.pesquisagravatai')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question')),
            ],
            options={
                'unique_together': {('response', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Texto exibido')),
                ('value', models.CharField(blank=True, help_text='Se vazio, usa o próprio texto exibido. Só mude se souber o que está fazendo — respostas antigas usam o valor salvo pra contar certo no dashboard.', max_length=255, verbose_name='Valor salvo (opcional)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('', '— nenhum —'), ('good', 'Ótimo (verde)'), ('warning', 'Neutro (amarelo)'), ('serious', 'Ruim (laranja)'), ('critical', 'Péssimo (vermelho)'), ('neutral', 'Sem opinião (cinza)')], default='', help_text='Preenchendo o status em todas as opções, a pergunta vira um gráfico de avaliação no dashboard.', max_length=20, verbose_name='Status (opcional)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.question')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('question', 'label')},
            },
        ),
    ]
