# Generated by Django 6.0.1 on 2026-08-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_old_fixed_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesquisagravatai',
            options={'verbose_name': 'Pesquisa respondida', 'verbose_name_plural': 'Pesquisas respondidas'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Opção de resposta', 'verbose_name_plural': 'Opções de resposta'},
        ),
    ]
