# Generated by Django 6.0.1 on 2026-08-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_alter_pesquisagravatai_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('radio', 'Escolha única'), ('checkbox_multi', 'Múltipla escolha'), ('text', 'Texto curto'), ('number', 'Número')], default='radio', max_length=20, verbose_name='Tipo de resposta'),
        ),
    ]
