# Generated by Django 6.0.1 on 2026-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisagravatai',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcada automaticamente: respostas idênticas enviadas em sequência rápida (flood/toque duplo no totem).', verbose_name='Duplicata'),
        ),
    ]
