# Generated by Django 6.0.1 on 2026-08-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_flag_duplicate_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisagravatai',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enviada em'),
        ),
    ]
